apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-cluster
  region: us-east-1
  version: "1.30"

managedNodeGroups:
  - name: roboshop-nginx
    amiFamily: AmazonLinux2
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20