apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: roboshop-cluster
  region: us-east-1
  version: "1.29"

managedNodeGroups:
  - name: roboshop-nginx
    instanceType: t3.medium
    desiredCapacity: 2
    maxSize: 3
    minSize: 1
    ssh:
      allow: true
